/* Copyright (c) Colorado School of Mines, 2013.*/
/* All rights reserved.                       */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cseis_jni_csNativeModuleHelp */

#ifndef _Included_cseis_jni_csNativeModuleHelp
#define _Included_cseis_jni_csNativeModuleHelp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cseis_jni_csNativeModuleHelp
 * Method:    native_moduleHtmlHelp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeModuleHelp_native_1moduleHtmlHelp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cseis_jni_csNativeModuleHelp
 * Method:    native_moduleHtmlExample
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeModuleHelp_native_1moduleHtmlExample
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cseis_jni_csNativeModuleHelp
 * Method:    native_moduleExample
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeModuleHelp_native_1moduleExample
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cseis_jni_csNativeModuleHelp
 * Method:    native_moduleHtmlListing
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeModuleHelp_native_1moduleHtmlListing
  (JNIEnv *, jobject);

/*
 * Class:     cseis_jni_csNativeModuleHelp
 * Method:    native_standardHeaderHtmlListing
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeModuleHelp_native_1standardHeaderHtmlListing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
