/* Copyright (c) Colorado School of Mines, 2013.*/
/* All rights reserved.                       */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cseis_jni_csNativeSegyReader */

#ifndef _Included_cseis_jni_csNativeSegyReader
#define _Included_cseis_jni_csNativeSegyReader
#ifdef __cplusplus
extern "C" {
#endif
#undef cseis_jni_csNativeSegyReader_HDR_MAP_STANDARD
#define cseis_jni_csNativeSegyReader_HDR_MAP_STANDARD 1110L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_OBC
#define cseis_jni_csNativeSegyReader_HDR_MAP_OBC 1111L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_SEND
#define cseis_jni_csNativeSegyReader_HDR_MAP_SEND 1112L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_ARMSS
#define cseis_jni_csNativeSegyReader_HDR_MAP_ARMSS 1113L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_PSEGY
#define cseis_jni_csNativeSegyReader_HDR_MAP_PSEGY 1114L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_NODE1
#define cseis_jni_csNativeSegyReader_HDR_MAP_NODE1 1115L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_NODE2
#define cseis_jni_csNativeSegyReader_HDR_MAP_NODE2 1116L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_SU
#define cseis_jni_csNativeSegyReader_HDR_MAP_SU 1117L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_SU_ONLY
#define cseis_jni_csNativeSegyReader_HDR_MAP_SU_ONLY 1118L
#undef cseis_jni_csNativeSegyReader_HDR_MAP_SU_BOTH
#define cseis_jni_csNativeSegyReader_HDR_MAP_SU_BOTH 1119L
#undef cseis_jni_csNativeSegyReader_NUM_DEFAULT_MAPS
#define cseis_jni_csNativeSegyReader_NUM_DEFAULT_MAPS 10L
/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_createInstance
 * Signature: (Ljava/lang/String;IIZZZ)J
 */
JNIEXPORT jlong JNICALL Java_cseis_jni_csNativeSegyReader_native_1createInstance
  (JNIEnv *, jobject, jstring, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_closeFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegyReader_native_1closeFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_sampleByteSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegyReader_native_1sampleByteSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_numTraces
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegyReader_native_1numTraces
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_numSamples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegyReader_native_1numSamples
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_numHeaders
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegyReader_native_1numHeaders
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_sampleInt
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_cseis_jni_csNativeSegyReader_native_1sampleInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_hdrIntValue
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegyReader_native_1hdrIntValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_hdrFloatValue
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_cseis_jni_csNativeSegyReader_native_1hdrFloatValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_hdrDoubleValue
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_cseis_jni_csNativeSegyReader_native_1hdrDoubleValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_getNextTrace
 * Signature: (J[FLcseis/seis/csSeismicTrace;)Z
 */
JNIEXPORT jboolean JNICALL Java_cseis_jni_csNativeSegyReader_native_1getNextTrace
  (JNIEnv *, jobject, jlong, jfloatArray, jobject);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_moveToTrace
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_cseis_jni_csNativeSegyReader_native_1moveToTrace
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_setHeaderToPeek
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegyReader_native_1setHeaderToPeek
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_peekHeaderValue
 * Signature: (JILcseis/seis/csHeader;)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegyReader_native_1peekHeaderValue
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_binHeader
 * Signature: (JLcseis/seis/csSegyBinHeader;)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegyReader_native_1binHeader
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_charHeader
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeSegyReader_native_1charHeader
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_headerName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeSegyReader_native_1headerName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_headerDesc
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeSegyReader_native_1headerDesc
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_headerType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegyReader_native_1headerType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_setSelection
 * Signature: (JLjava/lang/String;Ljava/lang/String;IILcseis/jni/csISelectionNotifier;)Z
 */
JNIEXPORT jboolean JNICALL Java_cseis_jni_csNativeSegyReader_native_1setSelection
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint, jobject);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_getNumSelectedTraces
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegyReader_native_1getNumSelectedTraces
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_getSelectedValues
 * Signature: (JLcseis/jni/csSelectedHeaderBundle;)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegyReader_native_1getSelectedValues
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_freeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegyReader_native_1freeInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegyReader
 * Method:    native_trcHeaderMap
 * Signature: (ILcseis/jni/csSegyTrcHeaderDefinition;)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegyReader_native_1trcHeaderMap
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
