/* Copyright (c) Colorado School of Mines, 2013.*/
/* All rights reserved.                       */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cseis_jni_csNativeSegdReader */

#ifndef _Included_cseis_jni_csNativeSegdReader
#define _Included_cseis_jni_csNativeSegdReader
#ifdef __cplusplus
extern "C" {
#endif
#undef cseis_jni_csNativeSegdReader_RECORDING_SYSTEM_SEAL
#define cseis_jni_csNativeSegdReader_RECORDING_SYSTEM_SEAL 121L
#undef cseis_jni_csNativeSegdReader_RECORDING_SYSTEM_GEORES
#define cseis_jni_csNativeSegdReader_RECORDING_SYSTEM_GEORES 122L
#undef cseis_jni_csNativeSegdReader_RECORDING_SYSTEM_GECO
#define cseis_jni_csNativeSegdReader_RECORDING_SYSTEM_GECO 123L
#undef cseis_jni_csNativeSegdReader_NAV_HEADER_NONE
#define cseis_jni_csNativeSegdReader_NAV_HEADER_NONE 200L
#undef cseis_jni_csNativeSegdReader_NAV_HEADER_PSI
#define cseis_jni_csNativeSegdReader_NAV_HEADER_PSI 201L
#undef cseis_jni_csNativeSegdReader_NAV_HEADER_LABO
#define cseis_jni_csNativeSegdReader_NAV_HEADER_LABO 202L
#undef cseis_jni_csNativeSegdReader_NAV_HEADER_HYDRONAV_VER1
#define cseis_jni_csNativeSegdReader_NAV_HEADER_HYDRONAV_VER1 203L
#undef cseis_jni_csNativeSegdReader_NAV_HEADER_HYDRONAV_VER6
#define cseis_jni_csNativeSegdReader_NAV_HEADER_HYDRONAV_VER6 204L
/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_createInstance
 * Signature: (Ljava/lang/String;ZZZII)J
 */
JNIEXPORT jlong JNICALL Java_cseis_jni_csNativeSegdReader_native_1createInstance
  (JNIEnv *, jobject, jstring, jboolean, jboolean, jboolean, jint, jint);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_closeFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegdReader_native_1closeFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_numTraces
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegdReader_native_1numTraces
  (JNIEnv *, jobject, jlong );

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_numSamples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegdReader_native_1numSamples
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_numHeaders
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegdReader_native_1numHeaders
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_sampleInt
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_cseis_jni_csNativeSegdReader_native_1sampleInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_hdrIntValue
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegdReader_native_1hdrIntValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_hdrFloatValue
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_cseis_jni_csNativeSegdReader_native_1hdrFloatValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_hdrDoubleValue
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_cseis_jni_csNativeSegdReader_native_1hdrDoubleValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_getNextTrace
 * Signature: (J[FLcseis/seis/csSeismicTrace;)Z
 */
JNIEXPORT jboolean JNICALL Java_cseis_jni_csNativeSegdReader_native_1getNextTrace
  (JNIEnv *, jobject, jlong, jfloatArray, jobject);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_moveToTrace
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_cseis_jni_csNativeSegdReader_native_1moveToTrace
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_headerName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeSegdReader_native_1headerName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_headerDesc
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cseis_jni_csNativeSegdReader_native_1headerDesc
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_headerType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cseis_jni_csNativeSegdReader_native_1headerType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cseis_jni_csNativeSegdReader
 * Method:    native_freeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeSegdReader_native_1freeInstance
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
