/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cseis_jni_csNativeFilter */

#ifndef _Included_cseis_jni_csNativeFilter
#define _Included_cseis_jni_csNativeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cseis_jni_csNativeFilter
 * Method:    native_createInstance
 * Signature: (IFFFFF)J
 */
JNIEXPORT jlong JNICALL Java_cseis_jni_csNativeFilter_native_1createInstance
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     cseis_jni_csNativeFilter
 * Method:    native_performFilter
 * Signature: (J[F[F)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeFilter_native_1performFilter
  (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray);

/*
 * Class:     cseis_jni_csNativeFilter
 * Method:    native_freeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeFilter_native_1freeInstance
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
