/* Copyright (c) Colorado School of Mines, 2013.*/
/* All rights reserved.                       */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cseis_jni_csNativeFFTTransform */

#ifndef _Included_cseis_jni_csNativeFFTTransform
#define _Included_cseis_jni_csNativeFFTTransform
#ifdef __cplusplus
extern "C" {
#endif
#undef cseis_jni_csNativeFFTTransform_FORWARD
#define cseis_jni_csNativeFFTTransform_FORWARD 1L
#undef cseis_jni_csNativeFFTTransform_INVERSE
#define cseis_jni_csNativeFFTTransform_INVERSE 2L
/*
 * Class:     cseis_jni_csNativeFFTTransform
 * Method:    native_performFFT
 * Signature: (I[DI)V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csNativeFFTTransform_native_1performFFT
  (JNIEnv *, jobject, jint, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif

