/* Copyright (c) Colorado School of Mines, 2013.*/
/* All rights reserved.                       */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cseis_jni_csJNIDef */

#ifndef _Included_cseis_jni_csJNIDef
#define _Included_cseis_jni_csJNIDef
#ifdef __cplusplus
extern "C" {
#endif
#undef cseis_jni_csJNIDef_DOMAIN_UNKNOWN
#define cseis_jni_csJNIDef_DOMAIN_UNKNOWN -1L
#undef cseis_jni_csJNIDef_DOMAIN_XT
#define cseis_jni_csJNIDef_DOMAIN_XT 110L
#undef cseis_jni_csJNIDef_DOMAIN_FX
#define cseis_jni_csJNIDef_DOMAIN_FX 111L
#undef cseis_jni_csJNIDef_DOMAIN_FK
#define cseis_jni_csJNIDef_DOMAIN_FK 112L
#undef cseis_jni_csJNIDef_DOMAIN_KT
#define cseis_jni_csJNIDef_DOMAIN_KT 113L
#undef cseis_jni_csJNIDef_DOMAIN_XD
#define cseis_jni_csJNIDef_DOMAIN_XD 114L
#undef cseis_jni_csJNIDef_VERTICAL_DOMAIN_TIME
#define cseis_jni_csJNIDef_VERTICAL_DOMAIN_TIME 1001L
#undef cseis_jni_csJNIDef_VERTICAL_DOMAIN_DEPTH
#define cseis_jni_csJNIDef_VERTICAL_DOMAIN_DEPTH 1002L
#undef cseis_jni_csJNIDef_VERTICAL_DOMAIN_FREQ
#define cseis_jni_csJNIDef_VERTICAL_DOMAIN_FREQ 1003L
#undef cseis_jni_csJNIDef_SORT_NONE
#define cseis_jni_csJNIDef_SORT_NONE 0L
#undef cseis_jni_csJNIDef_SORT_INCREASING
#define cseis_jni_csJNIDef_SORT_INCREASING 1L
#undef cseis_jni_csJNIDef_SORT_DECREASING
#define cseis_jni_csJNIDef_SORT_DECREASING 2L
#undef cseis_jni_csJNIDef_SIMPLE_SORT
#define cseis_jni_csJNIDef_SIMPLE_SORT 101L
#undef cseis_jni_csJNIDef_TREE_SORT
#define cseis_jni_csJNIDef_TREE_SORT 102L
#undef cseis_jni_csJNIDef_TYPE_UNKNOWN
#define cseis_jni_csJNIDef_TYPE_UNKNOWN 255L
#undef cseis_jni_csJNIDef_TYPE_INT
#define cseis_jni_csJNIDef_TYPE_INT 1L
#undef cseis_jni_csJNIDef_TYPE_FLOAT
#define cseis_jni_csJNIDef_TYPE_FLOAT 2L
#undef cseis_jni_csJNIDef_TYPE_DOUBLE
#define cseis_jni_csJNIDef_TYPE_DOUBLE 3L
#undef cseis_jni_csJNIDef_TYPE_CHAR
#define cseis_jni_csJNIDef_TYPE_CHAR 4L
#undef cseis_jni_csJNIDef_TYPE_STRING
#define cseis_jni_csJNIDef_TYPE_STRING 5L
#undef cseis_jni_csJNIDef_TYPE_LONG
#define cseis_jni_csJNIDef_TYPE_LONG 6L
/*
 * Class:     cseis_jni_csJNIDef
 * Method:    native_setJavaClassIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cseis_jni_csJNIDef_native_1setJavaClassIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
